version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: lena_help
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend: 
    image: barbarisko/item-tracker-back:latest
    restart: always
    environment:
      DB_ADDRESS: db,
      DB_PORT: 5432,
      DB_PWD: lena_help

  frontend: 
    image: barbarisko/item-tracker-front:latest
    restart: always
    ports:
      - "90:80"
  
volumes:
  db-data:
    driver: local