version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: lena_help
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend: 
    image: olena/item-tracker-back:latest
    restart: always
    environment:
      DB_ADDRESS: db,
      DB_PORT: 5432,
      DB_PWD: lena_help
    ports:
      - "5000:5000"

  frontend: 
    image: olena/item-tracker-front:latest
    restart: always
    ports:
      - "5173:5173"

  nginx: 
    image: nginx:latest
  
volumes:
  db-data:
    driver: local